spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:boost
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
